import React from "react";
import { useUserContext } from "../contexts/CurrentUser.Context";
import { useAppConfigContext } from "../contexts/AppConfig.context";
import {
  collection,
  doc,
  getCountFromServer,
  getDoc,
  query,
  serverTimestamp,
  setDoc,
  Timestamp,
  where,
} from "firebase/firestore";
import { db } from "../firebase/firebase";
import { useState } from "react";

const Summary = () => {
  const { currentUser, stationName } = useUserContext();
  const { stations } = useAppConfigContext();
  const [staffOrdCt, setStaffOrdCt] = useState("");
  const [statOrdCt, setStatOrdCt] = useState("");
  const mockOrders = [
    {
      id: "a1b2c3",
      customerId: "C001",
      customerName: "John Doe",
      customerAddress: "123 Main St, Lagos",
      originStation: "Head Office",
      originStationId: "HO001",
      destinationStation: "Okene 1",
      destinationStationId: "OK001",
      intraState: "No",
      intraCity: "No",
      deliveryType: "Station to Delivery man",
      deliveryService: "Regular",
      receiver: {
        firstName: "Jane",
        lastName: "Doe",
        businessName: "",
        phoneNumber: "123-456-7890",
        address: {
          state: "Kogi",
          lga: "Okene",
          streetAddress: "456 Park Ave",
        },
      },
      item: {
        description: "Computer monitor",
        value: "1000",
        weight: "20",
        quantity: "1",
        category: "Electronics",
        condition: "New",
      },
      insurance: "No",
      freightPrice: "200",
      additionalCharges: {},
      totalAdditionalCharges: "0",
      subtotal: "1200",
      VAT: "120",
      total: "1320",
      payOnDelivery: "Yes",
      paymentMode: "Cash",
      receiptInfo: "",
      paid: false,
      processedBy: "",
    },
    {
      id: "d4e5f6",
      customerId: "C002",
      customerName: "Jane Smith",
      customerAddress: "789 Elm St, Abuja",
      originStation: "Okene 1",
      originStationId: "OK001",
      destinationStation: "Ibadan 1",
      destinationStationId: "IB001",
      intraState: "No",
      intraCity: "No",
      deliveryType: "Interstation",
      deliveryService: "Express Delivery",
      receiver: {
        firstName: "Mike",
        lastName: "Johnson",
        businessName: "",
        phoneNumber: "234-567-8901",
        address: {
          state: "Oyo",
          lga: "Ibadan",
          streetAddress: "987 Oak St",
        },
      },
      item: {
        description: "Office chair",
        value: "500",
        weight: "15",
        quantity: "2",
        category: "Furniture",
        condition: "Used",
      },
      insurance: "Yes",
      freightPrice: "150",
      additionalCharges: {},
      totalAdditionalCharges: "0",
      subtotal: "1100",
      VAT: "110",
      total: "1210",
      payOnDelivery: "No",
      paymentMode: "Card",
      receiptInfo: "",
      paid: false,
      processedBy: "",
    },
    {
      id: "g7h8i9",
      customerId: "C003",
      customerName: "Mark Williams",
      customerAddress: "654 Pine St, Port Harcourt",
      originStation: "Ibadan 1",
      originStationId: "IB001",
      destinationStation: "Head Office",
      destinationStationId: "HO001",
      intraState: "Yes",
      intraCity: "No",
      deliveryType: "Pickup to Station",
      deliveryService: "Regular",
      receiver: {
        firstName: "Emily",
        lastName: "Jones",
        businessName: "",
        phoneNumber: "345-678-9012",
        address: {
          state: "Rivers",
          lga: "Port Harcourt",
          streetAddress: "321 Cedar St",
        },
      },
      item: {
        description: "Books",
        value: "200",
        weight: "10",
        quantity: "5",
        category: "Literature",
        condition: "New",
      },
      insurance: "No",
      freightPrice: "100",
      additionalCharges: {},
      totalAdditionalCharges: "0",
      subtotal: "1000",
      VAT: "100",
      total: "1100",
      payOnDelivery: "No",
      paymentMode: "Online Transfer",
      receiptInfo: "",
      paid: false,
      processedBy: "",
    },
    {
      id: "j1k2l3",
      customerId: "C004",
      customerName: "Ashley Taylor",
      customerAddress: "246 Birch St, Kano",
      originStation: "Head Office",
      originStationId: "HO001",
      destinationStation: "Okene 1",
      destinationStationId: "OK001",
      intraState: "No",
      intraCity: "Yes",
      deliveryType: "Pickup to Delivery man",
      deliveryService: "Express Delivery",
      receiver: {
        firstName: "Michael",
        lastName: "Brown",
        businessName: "",
        phoneNumber: "456-789-0123",
        address: {
          state: "Kano",
          lga: "Kano",
          streetAddress: "159 Maple St",
        },
      },
      item: {
        description: "Clothes",
        value: "300",
        weight: "5",
        quantity: "10",
        category: "Fashion",
        condition: "Used",
      },
      insurance: "Yes",
      freightPrice: "50",
      additionalCharges: {},
      totalAdditionalCharges: "0",
      subtotal: "850",
      VAT: "85",
      total: "935",
      payOnDelivery: "No",
      paymentMode: "Cheque",
      receiptInfo: "",
      paid: false,
      processedBy: "",
    },
    {
      id: "m4n5o6",
      customerId: "C005",
      customerName: "Jessica Davis",
      customerAddress: "369 Oak St, Uyo",
      originStation: "Okene 1",
      originStationId: "OK001",
      destinationStation: "Ibadan 1",
      destinationStationId: "IB001",
      intraState: "Yes",
      intraCity: "No",
      deliveryType: "Station to Delivery man",
      deliveryService: "Regular",
      receiver: {
        firstName: "Matthew",
        lastName: "Miller",
        businessName: "",
        phoneNumber: "567-890-1234",
        address: {
          state: "Akwa Ibom",
          lga: "Uyo",
          streetAddress: "753 Cherry St",
        },
      },
      item: {
        description: "Shoes",
        value: "150",
        weight: "3",
        quantity: "5",
        category: "Footwear",
        condition: "New",
      },
      insurance: "No",
      freightPrice: "75",
      additionalCharges: {},
      totalAdditionalCharges: "0",
      subtotal: "837.5",
      VAT: "83.75",
      total: "921.25",
      payOnDelivery: "Yes",
      paymentMode: "Cash",
      receiptInfo: "",
      paid: false,
      processedBy: "",
    },
    {
      id: "p7q8r9",
      customerId: "C006",
      customerName: "Sarah Anderson",
      customerAddress: "159 Maple St, Enugu",
      originStation: "Ibadan 1",
      originStationId: "IB001",
      destinationStation: "Head Office",
      destinationStationId: "HO001",
      intraState: "Yes",
      intraCity: "No",
      deliveryType: "Interstation",
      deliveryService: "Express Delivery",
      receiver: {
        firstName: "William",
        lastName: "Moore",
        businessName: "",
        phoneNumber: "678-901-2345",
        address: {
          state: "Enugu",
          lga: "Enugu",
          streetAddress: "753 Cherry St",
        },
      },
      item: {
        description: "Smartphone",
        value: "800",
        weight: "8",
        quantity: "1",
        category: "Electronics",
        condition: "New",
      },
      insurance: "Yes",
      freightPrice: "100",
      additionalCharges: {},
      totalAdditionalCharges: "0",
      subtotal: "900",
      VAT: "90",
      total: "990",
      payOnDelivery: "No",
      paymentMode: "Card",
      receiptInfo: "",
      paid: false,
      processedBy: "",
    },
    {
      id: "s1t2u3",
      customerId: "C007",
      customerName: "Michael Thomas",
      customerAddress: "369 Oak St, Jalingo",
      originStation: "Head Office",
      originStationId: "HO001",
      destinationStation: "Okene 1",
      destinationStationId: "OK001",
      intraState: "Yes",
      intraCity: "No",
      deliveryType: "Pickup to Station",
      deliveryService: "Regular",
      receiver: {
        firstName: "David",
        lastName: "Jackson",
        businessName: "",
        phoneNumber: "789-012-3456",
        address: {
          state: "Taraba",
          lga: "Jalingo",
          streetAddress: "246 Birch St",
        },
      },
      item: {
        description: "Kitchenware",
        value: "400",
        weight: "10",
        quantity: "4",
        category: "Household",
        condition: "Used",
      },
      insurance: "No",
      freightPrice: "80",
      additionalCharges: {},
      totalAdditionalCharges: "0",
      subtotal: "1440",
      VAT: "144",
      total: "1584",
      payOnDelivery: "No",
      paymentMode: "Online Transfer",
      receiptInfo: "",
      paid: false,
      processedBy: "",
    },
    {
      id: "v4w5x6",
      customerId: "C008",
      customerName: "Jessica Anderson",
      customerAddress: "789 Elm St, Calabar",
      originStation: "Okene 1",
      originStationId: "OK001",
      destinationStation: "Ibadan 1",
      destinationStationId: "IB001",
      intraState: "Yes",
      intraCity: "No",
      deliveryType: "Pickup to Delivery man",
      deliveryService: "Express Delivery",
      receiver: {
        firstName: "Daniel",
        lastName: "Lewis",
        businessName: "",
        phoneNumber: "890-123-4567",
        address: {
          state: "Cross River",
          lga: "Calabar",
          streetAddress: "654 Pine St",
        },
      },
      item: {
        description: "Bedding",
        value: "250",
        weight: "5",
        quantity: "8",
        category: "Bedroom",
        condition: "Used",
      },
      insurance: "Yes",
      freightPrice: "50",
      additionalCharges: {},
      totalAdditionalCharges: "0",
      subtotal: "2000",
      VAT: "200",
      total: "2200",
      payOnDelivery: "No",
      paymentMode: "Cheque",
      receiptInfo: "",
      paid: false,
      processedBy: "",
    },
    {
      id: "y7z8a1",
      customerId: "C009",
      customerName: "Sarah Thomas",
      customerAddress: "123 Main St, Lokoja",
      originStation: "Ibadan 1",
      originStationId: "IB001",
      destinationStation: "Head Office",
      destinationStationId: "HO001",
      intraState: "Yes",
      intraCity: "No",
      deliveryType: "Station to Delivery man",
      deliveryService: "Regular",
      receiver: {
        firstName: "Matthew",
        lastName: "Moore",
        businessName: "",
        phoneNumber: "901-234-5678",
        address: {
          state: "Kogi",
          lga: "Lokoja",
          streetAddress: "753 Cherry St",
        },
      },
      item: {
        description: "Artwork",
        value: "500",
        weight: "5",
        quantity: "2",
        category: "Art",
        condition: "New",
      },
      insurance: "No",
      freightPrice: "75",
      additionalCharges: {},
      totalAdditionalCharges: "0",
      subtotal: "1050",
      VAT: "105",
      total: "1155",
      payOnDelivery: "Yes",
      paymentMode: "Cash",
      receiptInfo: "",
      paid: false,
      processedBy: "",
    },
    {
      id: "b2c3d4",
      customerId: "C010",
      customerName: "Amanda Lewis",
      customerAddress: "456 Park Ave, Zaria",
      originStation: "Head Office",
      originStationId: "HO001",
      destinationStation: "Okene 1",
      destinationStationId: "OK001",
      intraState: "No",
      intraCity: "No",
      deliveryType: "Station to Delivery man",
      deliveryService: "Regular",
      receiver: {
        firstName: "James",
        lastName: "Brown",
        businessName: "",
        phoneNumber: "012-345-6789",
        address: {
          state: "Kaduna",
          lga: "Zaria",
          streetAddress: "987 Oak St",
        },
      },
      item: {
        description: "CDs",
        value: "100",
        weight: "1",
        quantity: "20",
        category: "Music",
        condition: "Used",
      },
      insurance: "Yes",
      freightPrice: "50",
      additionalCharges: {},
      totalAdditionalCharges: "0",
      subtotal: "2000",
      VAT: "200",
      total: "2200",
      payOnDelivery: "No",
      paymentMode: "Card",
      receiptInfo: "",
      paid: false,
      processedBy: "",
    },
    {
      id: "e5f6g7",
      customerId: "C011",
      customerName: "David Scott",
      customerAddress: "159 Maple St, Abeokuta",
      originStation: "Okene 1",
      originStationId: "OK001",
      destinationStation: "Ibadan 1",
      destinationStationId: "IB001",
      intraState: "Yes",
      intraCity: "No",
      deliveryType: "Pickup to Station",
      deliveryService: "Express Delivery",
      receiver: {
        firstName: "Daniel",
        lastName: "Hall",
        businessName: "",
        phoneNumber: "234-567-8901",
        address: {
          state: "Ogun",
          lga: "Abeokuta",
          streetAddress: "246 Birch St",
        },
      },
      item: {
        description: "Furniture",
        value: "600",
        weight: "15",
        quantity: "3",
        category: "Home",
        condition: "New",
      },
      insurance: "No",
      freightPrice: "90",
      additionalCharges: {},
      totalAdditionalCharges: "0",
      subtotal: "1770",
      VAT: "177",
      total: "1947",
      payOnDelivery: "No",
      paymentMode: "Online Transfer",
      receiptInfo: "",
      paid: false,
      processedBy: "",
    },
    {
      id: "h8i9j0",
      customerId: "C012",
      customerName: "George Turner",
      customerAddress: "369 Oak St, Benin City",
      originStation: "Ibadan 1",
      originStationId: "IB001",
      destinationStation: "Head Office",
      destinationStationId: "HO001",
      intraState: "Yes",
      intraCity: "No",
      deliveryType: "Interstation",
      deliveryService: "Regular",
      receiver: {
        firstName: "Anthony",
        lastName: "Parker",
        businessName: "",
        phoneNumber: "345-678-9012",
        address: {
          state: "Edo",
          lga: "Benin City",
          streetAddress: "321 Cedar St",
        },
      },
      item: {
        description: "Laptops",
        value: "1000",
        weight: "10",
        quantity: "2",
        category: "Electronics",
        condition: "Used",
      },
      insurance: "Yes",
      freightPrice: "80",
      additionalCharges: {},
      totalAdditionalCharges: "0",
      subtotal: "2080",
      VAT: "208",
      total: "2288",
      payOnDelivery: "Yes",
      paymentMode: "Cash",
      receiptInfo: "",
      paid: false,
      processedBy: "",
    },
  ];
  const date = new Date();
  mockOrders.forEach(async (order) => {
    const orderRef = doc(db, "orders", order.id);
    const snapshot = await getDoc(orderRef);
    if (!snapshot.exists()) {
      setDoc(orderRef, {
        ...order,
        tripId: "",
        deliveryStatus: "Order Received",
        trackingInfo: [
          {
            info: "Order Accepted at Origin Station",
            time: date.toLocaleString(),
          },
        ],
        dateCreated: serverTimestamp(),
      });
    }
  });
  const today = new Date().toDateString();
  const staffOrderCount = async () => {
    const ordersRef = collection(db, "orders");
    const q = query(
      ordersRef,

      where("dateCreated", ">=", Timestamp.fromDate(new Date(today))),
      where("processedBy", "==", currentUser.id)
    );
    const snapshot = await getCountFromServer(q);
    setStaffOrdCt(snapshot.data().count);
  };
  const stationOrderCount = async () => {
    const ordersRef = collection(db, "orders");
    const q = query(
      ordersRef,

      where("dateCreated", ">=", Timestamp.fromDate(new Date(today))),
      where("originStation", "==", stationName)
    );
    const snapshot = await getCountFromServer(q);
    setStatOrdCt(snapshot.data().count);
  };
  staffOrderCount();
  stationOrderCount();

  const userData = {
    "Station Name": stationName,
    "User ID": currentUser.id,
    Role: currentUser.role,
    Rank: currentUser.rank,
    "Staff Order Count": staffOrdCt,
    "Station Order count": statOrdCt,
    "Station Incoming Count": 0,
    "Station Warehouse": 0,
  };
  return (
    <div>
      <div className="w-full flex justify-between text-pink-600 mb-16">
        <p className="italic">
          Welcome back <span>{currentUser.displayName}</span>
        </p>
        <p>{new Date().toDateString()}</p>
      </div>
      <div className="flex flex-wrap w-full justify-center gap-4">
        {Object.keys(userData).map((key) => (
          <div
            key={key}
            className="text-center min-w-[230px] bg-teal-400 p-10 rounded-xl"
          >
            <p className="mb-3">{key}</p>
            <p>{userData[key]}</p>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Summary;
